#Create Sections(letter) with tables(number).
Section.create(letter: "A")
Section.create(letter: "B")
Section.create(letter: "C")
Table.create(number: "1", section_id:"1")
Table.create(number: "2", section_id:"1")
Table.create(number: "3", section_id:"1")
Table.create(number: "4", section_id:"1")
Table.create(number: "5", section_id:"1")
Table.create(number: "6", section_id:"2")
Table.create(number: "7", section_id:"2")
Table.create(number: "8", section_id:"2")
Table.create(number: "9", section_id:"2")
Table.create(number: "10", section_id:"2")
Table.create(number: "11", section_id:"3")
Table.create(number: "12", section_id:"3")
Table.create(number: "13", section_id:"3")
Table.create(number: "14", section_id:"3")
Table.create(number: "15", section_id:"3")
